"""Add separate geolocation fields to Attack model

Revision ID: 60c98d298730
Revises: b179af6c008c
Create Date: 2025-06-17 21:46:50.463860

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '60c98d298730'
down_revision = 'b179af6c008c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blocked_ip')
    op.drop_table('user')
    op.drop_table('attack')
    with op.batch_alter_table('attacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attacks', schema=None) as batch_op:
        batch_op.drop_column('city')
        batch_op.drop_column('country')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    op.create_table('attack',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=False),
    sa.Column('attack_vector', sa.VARCHAR(length=255), nullable=True),
    sa.Column('payload', sa.TEXT(), nullable=True),
    sa.Column('user_agent', sa.TEXT(), nullable=True),
    sa.Column('referer', sa.TEXT(), nullable=True),
    sa.Column('path', sa.VARCHAR(length=500), nullable=False),
    sa.Column('method', sa.VARCHAR(length=10), nullable=False),
    sa.Column('ai_prediction', sa.VARCHAR(length=100), nullable=True),
    sa.Column('rl_action_taken', sa.VARCHAR(length=100), nullable=True),
    sa.Column('geolocation_data', sqlite.JSON(), nullable=True),
    sa.Column('ip_reputation_data', sqlite.JSON(), nullable=True),
    sa.Column('status_code', sa.INTEGER(), nullable=True),
    sa.Column('headers', sa.TEXT(), nullable=True),
    sa.Column('attack_type', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('blocked_ip',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=False),
    sa.Column('blocked_until', sa.DATETIME(), nullable=False),
    sa.Column('reason', sa.VARCHAR(length=255), nullable=True),
    sa.Column('blocked_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address')
    )
    # ### end Alembic commands ###
