"""Add timestamp column to blocked_ip

Revision ID: 62ccfc1e021e
Revises: 60c98d298730
Create Date: 2025-06-18 16:15:40.303600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62ccfc1e021e'
down_revision = '60c98d298730'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.drop_table('users')
    op.drop_table('blocked_ips')
    op.drop_table('attacks')
    with op.batch_alter_table('attack', schema=None) as batch_op:
        batch_op.add_column(sa.Column('port', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('protocol', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('payload', sa.Text(), nullable=True))

    with op.batch_alter_table('blocked_ip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blocked_ip', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('attack', schema=None) as batch_op:
        batch_op.drop_column('payload')
        batch_op.drop_column('protocol')
        batch_op.drop_column('port')

    op.create_table('attacks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=False),
    sa.Column('attack_vector', sa.VARCHAR(length=255), nullable=True),
    sa.Column('payload', sa.TEXT(), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), nullable=True),
    sa.Column('referer', sa.VARCHAR(length=500), nullable=True),
    sa.Column('path', sa.VARCHAR(length=500), nullable=False),
    sa.Column('method', sa.VARCHAR(length=10), nullable=False),
    sa.Column('ai_prediction', sa.VARCHAR(length=100), nullable=True),
    sa.Column('rl_action_taken', sa.VARCHAR(length=100), nullable=True),
    sa.Column('headers', sa.TEXT(), nullable=True),
    sa.Column('geolocation_data', sa.TEXT(), nullable=True),
    sa.Column('ip_reputation_data', sa.TEXT(), nullable=True),
    sa.Column('attack_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitude', sa.FLOAT(), nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blocked_ips',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=False),
    sa.Column('blocked_until', sa.DATETIME(), nullable=False),
    sa.Column('blocked_at', sa.DATETIME(), nullable=False),
    sa.Column('reason', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(length=128), nullable=False),
    sa.Column('value', sa.VARCHAR(length=512), nullable=False),
    sa.Column('description', sa.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###
