"""Add attack_type column to Attack model

Revision ID: b179af6c008c
Revises: bad543e9ce40
Create Date: 2025-06-09 02:43:33.010391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b179af6c008c'
down_revision = 'bad543e9ce40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attack', schema=None) as batch_op:
        batch_op.add_column(sa.Column('headers', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('attack_type', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attack', schema=None) as batch_op:
        batch_op.drop_column('attack_type')
        batch_op.drop_column('headers')

    # ### end Alembic commands ###
