"""Add status_code column

Revision ID: db48b3dd3995
Revises: 
Create Date: 2025-06-07 22:11:51.239037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db48b3dd3995'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attack', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_code', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attack', schema=None) as batch_op:
        batch_op.drop_column('status_code')

    # ### end Alembic commands ###
